const AUTOMATIC_DEBT_TYPE = "automatic";
const MANUAL_DEBT_TYPE = "manual";
const CHARGE_EVERY_MONTH = "month";
const CHARGE_EVERY_NA = "N/A";

const DEBT_STATUS_PENDING = "pending";
const DEBT_STATUS_CHARGED = "charged";
const DEBT_STATUS_PAID = "paid";
const DEBT_STATUS_EXPIRED = "expired";
const DEBT_STATUS_CANCELLED = "cancelled";
const DEBT_STATUS_IN_REVIEW = "in review";

const PAYMENT_STATUS_PENDING = "pending";
const PAYMENT_STATUS_APPROVED = "approved";
const PAYMENT_STATUS_REJECTED = "rejected";
const PAYMENT_STATUS_IN_REVIEW = "in review";

const PAYMENT_COMMENT_STATUS_CREATED = "Pago subido por el usuario";
const PAYMENT_COMMENT_STATUS_UPDATED = "Pago actualizado por el usuario";
const PAYMENT_COMMENT_STATUS_APPROVED = "Pago aprobado por el administrador";

const JOB_STATUS_FAILED = "failed";
const JOB_STATUS_SUCCESS = "success";

module.exports = {
  AUTOMATIC_DEBT_TYPE,
  MANUAL_DEBT_TYPE,
  CHARGE_EVERY_MONTH,
  CHARGE_EVERY_NA,
  DEBT_STATUS_PENDING,
  DEBT_STATUS_CHARGED,
  DEBT_STATUS_PAID,
  DEBT_STATUS_EXPIRED,
  DEBT_STATUS_CANCELLED,
  DEBT_STATUS_IN_REVIEW,
  PAYMENT_STATUS_PENDING,
  PAYMENT_STATUS_APPROVED,
  PAYMENT_STATUS_REJECTED,
  PAYMENT_STATUS_IN_REVIEW,
  PAYMENT_COMMENT_STATUS_CREATED,
  PAYMENT_COMMENT_STATUS_APPROVED,
  PAYMENT_COMMENT_STATUS_UPDATED,
  JOB_STATUS_FAILED,
  JOB_STATUS_SUCCESS,
};
